### ISSUE TITLE
Redemrp -> Not Taking Money from Player

### ISSUE THREAD

**Issue by Duderocktv** [HALALsnackbar/rdn_companions#3]
Print _price and u_money at correct values
When reaching user.removeMoney(_price) it does not remove the money from wallet
Allows me to purchase the pet anyways

No errors client or server side

**Comment by HALALsnackbar** [comment]
This should be fixed with [this](https://github.com/HALALsnackbar/rdn_companions/commit/e8dd9a56835b836b300d92e4228c2e4f832c461e)
